### ISSUE TITLE
Link doesn't work.

### ISSUE THREAD

**Issue by nlok5923** [iiitv/hackiiitv#23]
provided mongodb link in setup requirements section of readme file doesn't work(404).

![Screenshot (1322)](https://user-images.githubusercontent.com/56120084/92319439-03d75800-efcd-11ea-9d0e-6cbb5896de9a.png)

i would like to work on this issue.

**Comment by nlok5923** [comment]
@iiitv/project-maintainers please let me know about the validity of this issue.

**Comment by anshumanv** [comment]
yep invalid, fix it
